spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
  http:
    encoding:
      charset: UTF-8
      force: true

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: mapper/*.xml

debug: true

server:
  port: 8888